
const fs = require('fs');

const filename = './src/ts/generated/package_version.ts';

const package = require('../../package.json');

const data_template = `
// Generated by %proj%/src/build_js/write_version_file.js

export {
  version     = '${package.version}',
  packagename = '${package.name}'
};
`;

fs.writeFileSync(filename, data_template, { flag: 'w', encoding: 'utf8'});

console.log(`# Wrote version file as ${package.name} ${package.version}; finished`);
